site_name: Motion Capture Lab Documentation

nav:
  - Home: index.md
  - Tutorials:
    - Tutorial 1: tutorials/tutorial1.md
    - Tutorial 2: tutorials/tutorial2.md
  - How-to Guides:
    - Guide 1: guides/guide1.md
    - Guide 2: guides/guide2.md
  - Explanations:
    - Explanation 1: explanations/explanation1.md
    - Explanation 2: explanations/explanation2.md
  - References:
    - Reference 1: references/reference1.md
    - Reference 2: references/reference2.md
  - About:
    - About Us: about/about.md
    - Contact Us: about/contact.md

theme:
  name: material

  

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: red
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: purple
      accent: lime


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/mocapmike  target="_blank" rel="noopener">Michael Nguyen</a> 